### ISSUE TITLE
重启VSCODE, 可以上传第一张图片. 之后全部网络错误.

### ISSUE THREAD

**Issue by HuBlanker** [Rackar/md-image-code-ext#13]
![image](https://user-images.githubusercontent.com/28507708/168605417-a4097b61-5592-4d0a-b530-c519906e0286.png)
目前是必现状态,重启vs, 可以上传成功第一张.之后全部是这个错误了.

**Comment by Rackar** [comment]
收到，谢谢反馈，尽快排查

**Comment by Rackar** [comment]
![image](https://user-images.githubusercontent.com/18388400/168799789-324fa339-a3f6-4bd1-a36b-fccf85b09d7e.png)

我测试正常。请检查一下网络连接、七牛的服务器设置及VScode配置，或者提供更多信息。
尤其是post请求这部分调用的是七牛sdk，没找到代码部分的嫌疑。

**Comment by HuBlanker** [comment]
辛苦测试了. 
我昨天测试时, 网络开有双层VPN(公司+**). 
看到你的回复, 刚才重新测试, 发现一次"socket hang up", 怀疑网络问题.
关闭掉双VPN后,  目前测试10次均成功.
因此问题可能是 vpn导致的七牛请求耗时增加,然后超时.
谢谢及时回复及排查.
