### ISSUE TITLE
插件用截图上传报错

### ISSUE THREAD

**Issue by qiaoyukeji** [Rackar/md-image-code-ext#18]
截图上传报错：
![image](https://user-images.githubusercontent.com/45252025/216822654-de58937f-9322-47f9-bdef-149c78953923.png)

```
上传失败，请检查网络连接。error: read ECONNRESET, POST http://up.qiniup.com -1 (connected: true, keepalive socket: true, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
```
选择本地上传，就能上传成功。

复现率100%。

**Comment by Rackar** [comment]
未能复现。请先检查下自己的网络对七牛上传地址的连通情况

![image](https://user-images.githubusercontent.com/18388400/216862364-20a2fc7b-96e3-40f3-bd0b-77e8b5dd93ec.png)
