### ISSUE TITLE
能否新增图片样式的支持？

### ISSUE THREAD

**Issue by xiaolongba** [Rackar/md-image-code-ext#19]
最近我们想要利用这个插件上传带水印的图片，我尝试在Qiniu: Remote Path
中指定样式，但不成功，例如：xxx.png-swyz(其中swyz是样式名)，但是最终变成xxx-sywz.png,这样导致水印增加失败；能否新增可以让样式放在xxx.png后面

提前感谢。

**Comment by Rackar** [comment]
没看懂这个需求，七牛的样式处理不是设置好后自动触发，然后通过自定义后缀来调用吗？ 

也就是在上传后在返回编辑器的`[img]`中手动加上样式后缀来引用。

**Comment by xiaolongba** [comment]
对，目前我们的后缀是sywz, 现在我们想利用咱们这个插件把这个后缀自动加到原始的图片链接后面，也就是xxx.png-swyz。这样我一粘贴，图片的链接会自动加上-sywz,这样就自动带水印了。

**Comment by xiaolongba** [comment]
其次，本地图片路径，在粘贴时能否不加一个.，如下：
![image](https://user-images.githubusercontent.com/16135532/228568666-b0826a7c-06a6-463b-a64f-157e28482456.png)

即把![1680079880670.png](./img/1680079880670.png)--->![1680079880670.png](/img/1680079880670.png)

因为有些Markdown加个.之后，无法解析这个图片，如gitlab就不支持。

**Comment by Rackar** [comment]
添加2个自定义设置，已发布。未测试，欢迎反馈

**Comment by xiaolongba** [comment]
> 添加2个自定义设置，已发布。未测试，欢迎反馈

老哥牛批，是在VSCODE市场吗？

**Comment by Rackar** [comment]
不测果然不行，已更新

**Comment by xiaolongba** [comment]
> 不测果然不行，已更新

属风流人物，还得老哥您😁
