### ISSUE TITLE
mac 和linux下脚本路径错误

### ISSUE THREAD

**Issue by ytl003** [Rackar/md-image-code-ext#4]
https://github.com/Rackar/md-image-code-ext/blob/9536f6a2883565cafd599df2304badfaa9f710f3/src/image.ts#L89

mac 和linux下脚本路径错误，麻烦作者修改一下

终于可以优雅的写markdown了哈哈😄

**Comment by Rackar** [comment]
已更新，没有Linux和Mac环境做测试。请帮忙反馈是否路径正常工作 :smiley:

**Comment by ytl003** [comment]
我本地打包了一个，测试没有问题
