### ISSUE TITLE
插入本地图片的路径格式（斜杠）建议修改

### ISSUE THREAD

**Issue by dlgcy** [Rackar/md-image-code-ext#6]
当前本地图片路径格式为：
`![1615432854630.png](images\1615432854630.png)`

建议改为：
`![1615432854630.png](/images/1615432854630.png)`

这样支持 Gitee

本地预览也正常：
![image](https://user-images.githubusercontent.com/5164143/110743002-4dea1080-8272-11eb-9df4-267fb52595b6.png)

**Comment by Rackar** [comment]
已修复为 ./相对路径格式， /在其他系统中是绝对根路径无法使用。
